FROM registry.access.redhat.com/ubi8/go-toolset:1.20

USER root

RUN dnf install -y \
        sudo git-core \
    && dnf clean all \
    && rm -rf /var/cache/yum

# Add user with the expected ID (automated setup does not work atm)
RUN useradd -l -u 1000 -G wheel -md /home/gbraad -s /usr/bin/zsh -p gbraad gbraad \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers

# install tailscale
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum

COPY scripts/tailscaled /etc/init.d/tailscaled

RUN dnf install -y \
        vim zsh \
    && dnf clean all \
    && rm -rf /var/cache/yum

# ssh server
RUN dnf install -y \
        openssh-server \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad